### ISSUE TITLE
BaseTest.waitForGrep should support a 'quiet' flag

### ISSUE THREAD

**Issue by rthrippleton** [pysys-test/pysys-test#39]
**Is your feature request related to a problem? Please describe the use case.**
I have a basetest with a large number of boilerplate setup actions, some of which require a waitForGrep to finish the setup. The more of this we have, the noisier our test output is, when ideally we'd only like to see things pertinent to that testcase.

**Describe the solution you'd like**
A 'quiet' boolean argument to waitForGrep such that waitForGrep will not cause any log output if quiet=True. It should still log on any sort of failure.

**Describe alternatives you've considered**
Re-implementing waitForGrep myself.

**Compatibility implications**
None, just another kwarg on the method

**Comment by ben-spiller** [comment]
this is implemented on the 1.6.2 dev branch
