### ISSUE TITLE
pysys run --mode should support globbing of modes

### ISSUE THREAD

**Issue by rthrippleton** [pysys-test/pysys-test#43]
**Is your feature request related to a problem? Please describe the use case.**
I have a project where we are using the mode string to support "multi-dimensional" modes e.g. `FirefoxEnglish, FirefoxFrench, ChromeEnglish, ChromeFrench` . This works really well, until we try to scale to a larger mode space.

If we want to run all tests against Firefox in one CI job, we have to enumerate every mode in our entrypoint script e.g.` pysys run --mode FirefoxEnglish,FirefoxFrench,FirefoxElvish, ...`     . This is mildly annoying, but also risks that we add a mode and forget to add it to all test jobs.

**Describe the solution you'd like**
`pysys run --mode` should support inclusion and exclusion based on globbing.

`pysys run --mode Firefox*` to run tests for all languages in just the Firefox browser.
`pysys run --mode !*Elvish` to run tests in all browsers for all languages except Elvish.

(if you feel free to submit and link a pull request - including testcases - if you want to try fixing it yourself)

**Describe alternatives you've considered**
We have an entrypoint script that greps the modes out of `pysys print --mode` and globs them itself, before automatically constructing the `pysys run` line. It's fine, but it's clearly a good feature to have 'upstream'.

**Compatibility implications**
No, unless asterisk is a valid character in a mode string.

**Comment by markhorsburgh** [comment]
I like it. I'm sure we'd find a use for it in our tests as well.

**Comment by ben-spiller** [comment]
When running tests we use regex rather than glob syntax for matching e.g. "pysys run MyTest.*". So to be consistent, shall we stick with regexes for matching modes too? (would need the leading ! for not to be handled differently, but that's do-able if a slightly grosss)

**Comment by rthrippleton** [comment]
@ben-spiller - Yeah, regex is absolutely fine if that's more consistent. I have no strong preference in favour of globbing; mostly I just forgot there was a difference.
