### ISSUE TITLE
python's getPreferredEncoding is not thread-safe

### ISSUE THREAD

**Issue by chrisreed-sag** [pysys-test/pysys-test#46]
Python's [locale.getpreferredencoding](https://docs.python.org/3/library/locale.html#locale.getpreferredencoding) is not thread safe : in particular, on Linux if LANG is set and a test is using .lower(), the result of .lower() (for non-ASCII characters) can change.

**Expected behavior**
Pysys (and, indeed tests) should avoid calling getpreferredencoding - better would be to store it in a global at startup and provide a getter function

**Affected version(s)**
- Python version(s): 3.7.8, 2.7.5
- PySys version(s): 1.6.1
- Operating System(s): Linux

**Comment by ben-spiller** [comment]
fixed by 0fad4a1
